version: 2
jobs:
  build:
    working_directory: ~/workdir
    docker:
      - image: gradle:5.4.1
    steps:
      - checkout
      - restore_cache:
          key: circleci-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-{{ checksum "build.gradle" }}
      - run: ./gradlew build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global